# Generated by Django 5.1.3 on 2024-12-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lager",
            fields=[
                (
                    "auto_increment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Barcode", models.CharField(max_length=30)),
                ("Bezeichnung", models.CharField(max_length=25)),
                ("Kategorie", models.CharField(max_length=20)),
                ("Lagerbestand", models.IntegerField(max_length=4)),
                ("Mindestbestand", models.IntegerField(max_length=4)),
            ],
        ),
    ]
