# Generated by Django 5.1.3 on 2024-12-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0002_lager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.RenameField(
            model_name="lager",
            old_name="auto_increment_id",
            new_name="id",
        ),
    ]
