# Generated by Django 5.1.3 on 2024-12-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0003_delete_customer_rename_auto_increment_id_lager_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lager",
            name="Lagerbestand",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="lager",
            name="Mindestbestand",
            field=models.IntegerField(),
        ),
    ]
